/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tampilan;
import Controller.SewaBukuController;
import FungsiCrud.CrudSewaBuku;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.Timer;

/**
 *
 * @author IndahAulia
 */
public class tampilanGUI extends javax.swing.JFrame {

    /**
     * Creates new form tampilan
     */
    public tampilanGUI() {
        initComponents();
        Tanggal();
        CreateTable();
        Tampil_Jam();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        input_judul = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        total_biaya = new javax.swing.JLabel();
        lbl_harga = new javax.swing.JLabel();
        buku_simpan = new javax.swing.JButton();
        buku_kembali = new javax.swing.JButton();
        buku_edit = new javax.swing.JButton();
        buku_delete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelBuku = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jlabel_tanggal = new javax.swing.JLabel();
        jlabel_jam = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Judul : ");

        input_judul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                input_judulActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Biaya : ");

        total_biaya.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        total_biaya.setText("Rp");

        buku_simpan.setBackground(new java.awt.Color(0, 102, 102));
        buku_simpan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buku_simpan.setForeground(new java.awt.Color(255, 255, 255));
        buku_simpan.setText("Simpan");
        buku_simpan.setAlignmentY(0.0F);
        buku_simpan.setIconTextGap(0);
        buku_simpan.setInheritsPopupMenu(true);
        buku_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buku_simpanActionPerformed(evt);
            }
        });

        buku_kembali.setBackground(new java.awt.Color(0, 102, 102));
        buku_kembali.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buku_kembali.setForeground(new java.awt.Color(255, 255, 255));
        buku_kembali.setText("Kembalikan Buku");
        buku_kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buku_kembaliActionPerformed(evt);
            }
        });

        buku_edit.setBackground(new java.awt.Color(0, 102, 102));
        buku_edit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buku_edit.setForeground(new java.awt.Color(255, 255, 255));
        buku_edit.setText("Edit");
        buku_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buku_editActionPerformed(evt);
            }
        });

        buku_delete.setBackground(new java.awt.Color(0, 102, 102));
        buku_delete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buku_delete.setForeground(new java.awt.Color(255, 255, 255));
        buku_delete.setText("Delete");
        buku_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buku_deleteActionPerformed(evt);
            }
        });

        TabelBuku.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        TabelBuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Judul Buku", "Tanggal Pinjam", "Tanggal Harus Kembali", "Tanggal Kembali", "Denda", "Biaya Sewa"
            }
        ));
        TabelBuku.setToolTipText("");
        TabelBuku.setInheritsPopupMenu(true);
        TabelBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelBukuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelBuku);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Tanggal : ");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Jam : ");

        jlabel_tanggal.setText("tanggal");

        jlabel_jam.setText("jam");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlabel_tanggal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlabel_jam)
                .addGap(23, 23, 23))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jlabel_tanggal)
                    .addComponent(jlabel_jam))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Persewaan Buku XYZ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(input_judul, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(total_biaya)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_harga))
                            .addComponent(jLabel4)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(buku_simpan)
                            .addGap(36, 36, 36)
                            .addComponent(buku_kembali)
                            .addGap(37, 37, 37)
                            .addComponent(buku_edit)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                            .addComponent(buku_delete))))
                .addGap(159, 159, 159))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 823, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(input_judul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(total_biaya)
                    .addComponent(lbl_harga))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buku_simpan)
                    .addComponent(buku_kembali)
                    .addComponent(buku_edit)
                    .addComponent(buku_delete))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buku_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buku_simpanActionPerformed
       String _judulBuku = input_judul.getText().trim();
       if(_judulBuku.equals(""))
       {
           JOptionPane.showMessageDialog(this, "Input judul tidak boleh kosong!!","fail",JOptionPane.ERROR_MESSAGE);
           return;
       }
       CrudSewaBuku DAO = new CrudSewaBuku();
       SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dddd");
       
       String _tgl_Pinjam = formatter.format(tanggal);
       
       //bikin tanggal kembali
       Calendar c = Calendar.getInstance();
       c.setTime(tanggal);
       c.add(Calendar.DATE, 7);
       String _tgl_Kembali = formatter.format(c.getTime());
       DAO.InserNewData(_judulBuku, _tgl_Pinjam, _tgl_Kembali);
        JOptionPane.showMessageDialog(this, "Data berhasil dibuat!!");
        CreateTable();
        id_selected = 0;
                   input_judul.setText("");
                    total_biaya.setText("Rp");
    }//GEN-LAST:event_buku_simpanActionPerformed

    private void buku_kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buku_kembaliActionPerformed
       if(id_selected != 0){
           //kalau masih kosong
           if(tgl_kembali_selected.equals("")){
               CrudSewaBuku dao = new CrudSewaBuku();
               try {
                   dao.KembalikanBuku(id_selected);
                    JOptionPane.showMessageDialog(this, "Buku berhasil dikembalikan!!");
                   CreateTable();
                   id_selected = 0;
                   input_judul.setText("");
                    total_biaya.setText("Rp");
               } catch (ParseException ex) {
                   Logger.getLogger(tampilanGUI.class.getName()).log(Level.SEVERE, null, ex);
               }
           }else{
               JOptionPane.showMessageDialog(this, "Buku sudah dikembalikan","warning",JOptionPane.WARNING_MESSAGE);
           }
       }
       else{
             JOptionPane.showMessageDialog(this, "Tidak ada data yang terpilih","error",JOptionPane.ERROR_MESSAGE);
       }
    }//GEN-LAST:event_buku_kembaliActionPerformed

    private void buku_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buku_editActionPerformed
        if(id_selected != 0){
            
            //cek apakah sudah dikembalikan
            if(tgl_kembali_selected.equals("")){
                //cek apakah judul kosong
           String _judulBuku = input_judul.getText();
           if(_judulBuku.equals("")){
                JOptionPane.showMessageDialog(this, "Input judul tidak boleh kosong!!","error",JOptionPane.ERROR_MESSAGE);
           return;
           }
           else{
               CrudSewaBuku dao = new CrudSewaBuku();
               dao.UpdateData(id_selected, _judulBuku);
               JOptionPane.showMessageDialog(this, "Data berhasil terupdate!!");
        CreateTable();
         id_selected = 0;
                   input_judul.setText("");
                    total_biaya.setText("Rp");
           }
            }
            else{
                 JOptionPane.showMessageDialog(this, "Buku sudah dikembalikan, data tidak dapat diedit","warning",JOptionPane.WARNING_MESSAGE);
            }
            
           
        }
        else{
            JOptionPane.showMessageDialog(this, "Tidak ada data yang terpilih","error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buku_editActionPerformed

    private void buku_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buku_deleteActionPerformed
          if(id_selected != 0){
               CrudSewaBuku dao = new CrudSewaBuku();
               dao.DeleteData(id_selected);
               JOptionPane.showMessageDialog(this, "Data berhasil terhapus!!");
        CreateTable();
         id_selected = 0;
                   input_judul.setText("");
                    total_biaya.setText("Rp");
           }else{
              JOptionPane.showMessageDialog(this, "Tidak ada data yang terpilih","error",JOptionPane.ERROR_MESSAGE);
          }
    }//GEN-LAST:event_buku_deleteActionPerformed

    private void input_judulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_input_judulActionPerformed
       
    }//GEN-LAST:event_input_judulActionPerformed

    private void TabelBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelBukuMouseClicked
        int row = TabelBuku.rowAtPoint(evt.getPoint());
        id_selected = (int)TabelBuku.getValueAt(row,0);
       input_judul.setText(TabelBuku.getValueAt(row, 1).toString());
       tgl_kembali_selected = TabelBuku.getValueAt(row, 4).toString();
       int denda = (int)TabelBuku.getValueAt(row, 5);
       int sewa = (int)TabelBuku.getValueAt(row, 6);
       total_biaya.setText("Rp " +(denda+sewa));
    }//GEN-LAST:event_TabelBukuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tampilanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tampilanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tampilanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tampilanGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tampilanGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelBuku;
    private javax.swing.JButton buku_delete;
    private javax.swing.JButton buku_edit;
    private javax.swing.JButton buku_kembali;
    private javax.swing.JButton buku_simpan;
    private javax.swing.JTextField input_judul;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlabel_jam;
    private javax.swing.JLabel jlabel_tanggal;
    private javax.swing.JLabel lbl_harga;
    private javax.swing.JLabel total_biaya;
    // End of variables declaration//GEN-END:variables

    //variable
    SewaBukuController c_sewaBuku;
    SimpleDateFormat format_tanggal;
    SimpleDateFormat format_jam;
    Date tanggal;
    int id_selected;
    String tgl_kembali_selected;
    int biaya_sewa = 5000;
    
        void Tanggal() {
        format_tanggal = new SimpleDateFormat("dd MMMM yyyy");
        format_jam = new SimpleDateFormat("HH:mm:dd");
        tanggal = new Date();
        jlabel_tanggal.setText(format_tanggal.format(tanggal));
    }
        public void Tampil_Jam(){
        ActionListener taskPerformer = new ActionListener() {
 
        @Override
            public void actionPerformed(ActionEvent evt) {
            String nol_jam = "", nol_menit = "",nol_detik = "";
 
            java.util.Date dateTime = new java.util.Date();
            int nilai_jam = dateTime.getHours();
            int nilai_menit = dateTime.getMinutes();
            int nilai_detik = dateTime.getSeconds();
 
            if(nilai_jam <= 9) nol_jam= "0";
            if(nilai_menit <= 9) nol_menit= "0";
            if(nilai_detik <= 9) nol_detik= "0";
 
            String jam = nol_jam + Integer.toString(nilai_jam);
            String menit = nol_menit + Integer.toString(nilai_menit);
            String detik = nol_detik + Integer.toString(nilai_detik);
 
            jlabel_jam.setText(jam+":"+menit+":"+detik+"");
            }
        };
    new Timer(1000, taskPerformer).start();
    }
    
      public JTable GetTabelData(){
         return TabelBuku;
     }
    
     //fungsi menampilkan tabel hasil panen
     public void CreateTable(){
          c_sewaBuku = new SewaBukuController(this);
          c_sewaBuku.IsiTable();
     }
}