/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package formsewa;
import koneksi.konekdb;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Locale;
import javax.swing.Timer;
import java.time.Duration;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;



/**
 *
 * @author ASUS
 */
public class dataform extends javax.swing.JFrame {
    private DefaultTableModel DftTblModel_buku;
    private String SQL;

    /**
     * Creates new form dataform
     */
    public dataform() {
        initComponents();
        this.TampilData();
        this.Tampil_Jam();
        this.Tampil_Tanggal();
        this.TanggalKembali();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        judul_buku = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        simpan = new javax.swing.JButton();
        kembali_buku = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelbuku = new javax.swing.JTable();
        tanggal_kembali = new javax.swing.JLabel();
        total_biaya = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tanggal_sekarang = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jam_sekarang = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        label_id = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jTextPane1);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("Persewaan Buku XYZ");

        judul_buku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                judul_bukuActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Judul Buku :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Biaya : ");

        simpan.setText("simpan");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });

        kembali_buku.setText("kemabalikan buku");
        kembali_buku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembali_bukuActionPerformed(evt);
            }
        });

        edit.setText("Edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        delete.setText("Delete");
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        tabelbuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Judul Buku", "Tanggal Pinjam", "Tanggal Harus Kembali", "Tanggal Kembali", "Denda", "Biaya Sewa"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelbuku.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tabelbukuAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tabelbuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelbukuMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabelbuku);

        tanggal_kembali.setForeground(new java.awt.Color(204, 204, 204));
        tanggal_kembali.setText("         ");

        total_biaya.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        total_biaya.setText("Rp.");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Tangal : ");

        tanggal_sekarang.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tanggal_sekarang.setText("-");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Jam :");

        jam_sekarang.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jam_sekarang.setText("--");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tanggal_sekarang, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jam_sekarang, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tanggal_sekarang)
                    .addComponent(jLabel3)
                    .addComponent(jam_sekarang))
                .addGap(20, 20, 20))
        );

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Rp.");

        label_id.setForeground(new java.awt.Color(204, 204, 204));
        label_id.setText("ID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(185, 185, 185)
                                        .addComponent(jLabel5))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(kembali_buku, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tanggal_kembali)
                    .addComponent(label_id)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(judul_buku, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(130, 130, 130)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(total_biaya)))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(judul_buku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(total_biaya))
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kembali_buku, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delete, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(label_id)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tanggal_kembali)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void judul_bukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_judul_bukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_judul_bukuActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        try {
            int biayasewa = 5000;
            Connection conn = konekdb.getConnection();
            String query_InsertData = "INSERT INTO sewabuku (judul,tanggal_pinjam,tanggal_harus_kembali, biaya_sewa) VALUES (?,?,?,?)";
            PreparedStatement stmt = conn.prepareStatement(query_InsertData);
            stmt.setString(1, judul_buku.getText());
            stmt.setString(2, tanggal_sekarang.getText());
            stmt.setString(3, tanggal_kembali.getText());
            stmt.setInt(4, biayasewa);
            stmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data berhasil disimpan", "Pesan", JOptionPane.INFORMATION_MESSAGE);
            TampilData();
            
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        } // TODO add your handling code here:
    }//GEN-LAST:event_simpanActionPerformed

    private void tabelbukuAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tabelbukuAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tabelbukuAncestorAdded

    private void tabelbukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelbukuMouseClicked
        try {
            Connection conn = konekdb.getConnection();
            int row =tabelbuku.getSelectedRow();
            String tabel_klik=(tabelbuku.getModel().getValueAt(row, 0).toString());
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet sql = stm.executeQuery("select * from sewabuku where id='"+tabel_klik+"'");
            if(sql.next()){
                String id = sql.getString("id");
                label_id.setText(id);
                String nama = sql.getString("judul");
                judul_buku.setText(nama);
                String harga = sql.getString("biaya_sewa");
                total_biaya.setText(harga);
            }
            
        } catch (Exception e) {}   // TODO add your handling code here:
    }//GEN-LAST:event_tabelbukuMouseClicked

    private void kembali_bukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembali_bukuActionPerformed
         // TODO add your handling code here:
        int idselect = Integer.parseInt(label_id.getText());
        try {
            this.KembalikanBuku(idselect);
        } catch (ParseException ex) {
            Logger.getLogger(dataform.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(this, "Buku berhasil dikembalikan!!");
        TampilData();
    }//GEN-LAST:event_kembali_bukuActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
        try{
            String sql ="delete from sewabuku where id='"+label_id.getText()+"'";
            Connection conn = konekdb.getConnection();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data akan dihapus?");
            TampilData();
    
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "Data gagal di hapus" + e.getMessage(), "Pesan", JOptionPane.ERROR_MESSAGE);
            }       // TODO add your handling code here:
    }//GEN-LAST:event_deleteActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        try {
            String sql ="update sewabuku set judul = '"+judul_buku.getText()+"' where id='"+label_id.getText()+"'";
            Connection conn = konekdb.getConnection();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Data Terupdate");
            TampilData();    // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(dataform.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_editActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dataform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dataform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dataform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dataform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dataform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton delete;
    private javax.swing.JButton edit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel jam_sekarang;
    private javax.swing.JTextField judul_buku;
    private javax.swing.JButton kembali_buku;
    private javax.swing.JLabel label_id;
    private javax.swing.JButton simpan;
    private javax.swing.JTable tabelbuku;
    private javax.swing.JLabel tanggal_kembali;
    private javax.swing.JLabel tanggal_sekarang;
    private javax.swing.JLabel total_biaya;
    // End of variables declaration//GEN-END:variables
    
    
    public void TampilData() {
        DftTblModel_buku = new DefaultTableModel();
        DftTblModel_buku.addColumn("ID");
        DftTblModel_buku.addColumn("Judul Buku");
        DftTblModel_buku.addColumn("Tanggal Pinjam");
        DftTblModel_buku.addColumn("Tanggal Harus Kembali");
        DftTblModel_buku.addColumn("Tanggal Kembali");
        DftTblModel_buku.addColumn("Denda");
        DftTblModel_buku.addColumn("Biaya Sewa");
        tabelbuku.setModel(DftTblModel_buku);
        Connection conn = konekdb.getConnection();
        try {
            java.sql.Statement stmt = conn.createStatement();
            SQL = "select * from sewabuku";
            java.sql.ResultSet res = stmt.executeQuery(SQL);
            while (res.next()) {
                DftTblModel_buku.addRow(new Object[]{
                    res.getString("id"),
                    res.getString("judul"),
                    res.getString("tanggal_pinjam"),
                    res.getString("tanggal_harus_kembali"),
                    res.getString("tanggal_kembali"),
                    res.getString("denda"),
                    res.getString("biaya_sewa"),
                });
            }
        } catch (SQLException e) {
            System.out.println(e.getMessage());
        }
    }
    
    public void Tampil_Jam(){
        ActionListener taskPerformer = new ActionListener() {
 
        @Override
            public void actionPerformed(ActionEvent evt) {
            String nol_jam = "", nol_menit = "",nol_detik = "";
 
            java.util.Date dateTime = new java.util.Date();
            int nilai_jam = dateTime.getHours();
            int nilai_menit = dateTime.getMinutes();
            int nilai_detik = dateTime.getSeconds();
 
            if(nilai_jam <= 9) nol_jam= "0";
            if(nilai_menit <= 9) nol_menit= "0";
            if(nilai_detik <= 9) nol_detik= "0";
 
            String jam = nol_jam + Integer.toString(nilai_jam);
            String menit = nol_menit + Integer.toString(nilai_menit);
            String detik = nol_detik + Integer.toString(nilai_detik);
 
            jam_sekarang.setText(jam+":"+menit+":"+detik+"");
            }
        };
    new Timer(1000, taskPerformer).start();
    } 
    
    public void Tampil_Tanggal() {
    java.util.Date tglsekarang = new java.util.Date();
    SimpleDateFormat smpdtfmt = new SimpleDateFormat("yyyy-MM-dddd", Locale.getDefault());
    String tanggal = smpdtfmt.format(tglsekarang);
    tanggal_sekarang.setText(tanggal);
    }
    
    private void TanggalKembali() {
	SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dddd");
        int tambah = 7;
        Date tgl = new java.util.Date();
        Calendar calTambah = Calendar.getInstance();

        calTambah.setTime(tgl);
        calTambah.add(Calendar.DAY_OF_MONTH, tambah);

        tanggal_kembali.setText(sdf.format(calTambah.getTime()));

    }
    
    public String GetTanggalHarusKembali(int id){
        String tanggal_harusKembali = "";
        try{
            Connection conn = konekdb.getConnection();
            Statement st = conn.createStatement();
            String querry = "SELECT tanggal_harus_kembali FROM sewabuku WHERE id = "+id;
            System.out.println(querry);
            ResultSet rs = st.executeQuery(querry);
            while (rs.next()) {
                tanggal_harusKembali = rs.getString("tanggal_harus_kembali");
            }   
        }  
        catch(SQLException e){
            System.out.println("Error");
        }
        return tanggal_harusKembali;
    }
    
    
    public void KembalikanBuku(int id) throws ParseException{
        long denda = 2000;
        String _harusKembali = GetTanggalHarusKembali(id);
        Date harusKembali =new SimpleDateFormat("yyyy-MM-dddd").parse(_harusKembali);
        Date kembali = new Date();
     
        if(kembali.after(harusKembali)){
            SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
            String str1 = formatter.format(harusKembali);
            String str2 = formatter.format(kembali);
     
            LocalDate d1 = LocalDate.parse(str1, DateTimeFormatter.ISO_LOCAL_DATE);
            LocalDate d2 = LocalDate.parse(str2, DateTimeFormatter.ISO_LOCAL_DATE);
        
            Duration diff = Duration.between(d1.atStartOfDay(), d2.atStartOfDay());

            long diffDays = diff.toDays(); 
            denda=  denda * diffDays;
        }else{
          denda =  0;
        }
        
        UpdateTanggalKembaliBuku(denda,id);
}
    
    
    String query_updateKembaliBuku = "UPDATE sewabuku SET tanggal_kembali = ?,denda = ?  WHERE id = ?";
    public void UpdateTanggalKembaliBuku(long _denda,int id){
        PreparedStatement statement = null;
            try{
                Connection conn = konekdb.getConnection();
                statement = conn.prepareStatement(query_updateKembaliBuku);
              
                SimpleDateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
                Date dateNow = new Date();
              
                statement.setString(1,formatter.format(dateNow));
                statement.setLong(2, _denda);
                statement.setInt(3, id);
                statement.execute();
            }
            catch(SQLException e){
                System.out.println("Gagal"); 
            }
            finally{
                try {
                    statement.close();
                } catch (SQLException ex) {
                    System.out.println("Gagal");          
                }
            }
    }
    
}

